#!/usr/bin/env ruby
# vim: set filetype=ruby:
$: << File.expand_path('../../lib/', __FILE__)

require 'git-newline-at-eof'
require 'optparse'

feed_last_line = false
discard_last_newline = false
treat_all = false

opt = OptionParser.new
opt.on('-f', '--feed-last-line') { |v|
  feed_last_line = true
}
opt.on('-d', '--discard-last-newline') { |v|
  discard_last_newline = true
}
opt.on('-a', '--treat-all') { |v|
  treat_all = true
  feed_last_line = false
  discard_last_newline = false
}
opt.parse!(ARGV)

app = GitNewlineAtEof::Application.new
if treat_all
  app.treat_all
end
if feed_last_line
  app.feed_last_line_all
end
if discard_last_newline
  app.discard_last_newline_all
end
